version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "/dev-proxy"
    - "/dev-proxy-abstractions"
    - "/dev-proxy-plugins"
  schedule:
    interval: daily

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: daily