name: Create GitHub release
on:
  push:
    tags: ['v*']

jobs:
  publish_binaries:
    name: Publish binaries
    runs-on: [windows-latest]
    strategy:
      matrix:
        architecture:
          - win-x64
          - win-x86
          - linux-x64
          - osx-x64
          - osx-arm64
    env:
      release: 'dev-proxy-${{ matrix.architecture }}-${{ github.ref_name }}'
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Publish ${{ matrix.architecture }}
        run: dotnet publish ./dev-proxy/dev-proxy.csproj -c Release -p:PublishSingleFile=true -p:InformationalVersion=$("${{ github.ref_name }}".Substring(1)) -r ${{ matrix.architecture }} --self-contained -o ./${{ env.release }}
      - name: Build plugins
        run: dotnet build ./dev-proxy-plugins/dev-proxy-plugins.csproj -p:InformationalVersion=$("${{ github.ref_name }}".Substring(1)) -c Release -r ${{ matrix.architecture }} --no-self-contained
      - name: Add plugins to output
        run: cp ./dev-proxy/bin/Release/net8.0/${{ matrix.architecture }}/plugins ./${{ env.release }} -r
      - name: Remove unnecessary files
        run: |
          pushd
          cd ./${{ env.release }}
          Get-ChildItem -Filter *.pdb -Recurse | Remove-Item
          Get-ChildItem -Filter *.deps.json -Recurse | Remove-Item
          Get-ChildItem -Filter *.runtimeconfig.json -Recurse | Remove-Item
          popd
      - name: Archive Release ${{ env.release }}
        uses: thedoctor0/zip-release@master
        with:
          filename: '../${{ env.release }}.zip'
          directory: './${{ env.release }}'
      - uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ env.release }}
          path: ./${{ env.release }}.zip
  create_release:
    name: Create Release
    needs: [publish_binaries]
    environment:
      name: gh_releases
    runs-on: [windows-latest]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: output
      - name: Release
        uses: anton-yurchenko/git-release@v5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "true"
        with:
          args: |
              output/binaries-*/*.zip
