name: Create GitHub release
on:
  push:
    tags: ['v*']

jobs:
  publish_binaries:
    name: Publish binaries
    runs-on: [self-hosted, 1ES.Pool=1es-graphdevx-ubuntu-github-latest]
    strategy:
      matrix:
        architecture:
          - win-x64
          - win-x86
          - linux-x64
          - osx-x64
    env:
      release: 'msgraph-developer-proxy-${{ matrix.architecture }}-${{  github.ref_name }}'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Publish ${{ matrix.architecture }}
        run: dotnet publish ./msgraph-developer-proxy/msgraph-developer-proxy.csproj -c Release -p:PublishSingleFile=true -r ${{ matrix.architecture }} --self-contained -o ./${{ env.release }}
      - name: Build plugins
        run: dotnet build ./msgraph-developer-proxy-plugins/msgraph-developer-proxy-plugins.csproj -c Release -r ${{ matrix.architecture }} --no-self-contained
      - name: Add plugins to output
        run: cp ./msgraph-developer-proxy/bin/Release/net6.0/${{ matrix.architecture }}/GraphProxyPlugins ./${{ env.release }} -r
      - name: Archive Release ${{ env.release }}
        uses: thedoctor0/zip-release@master
        with:
          filename: '../${{ env.release }}.zip'
          directory: './${{ env.release }}'
      - uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ env.release }}
          path: ./${{ env.release }}.zip
  create_release:
    name: Create Release
    needs: [publish_binaries]
    environment:
      name: gh_releases
    runs-on: [self-hosted, 1ES.Pool=1es-graphdevx-ubuntu-github-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: output
      - name: Release
        uses: anton-yurchenko/git-release@v5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "true"
        with:
          args: |
              output/binaries-*/*.zip
