name: .NET # name must match the original workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: ['samples/**', '**.md', '.vscode/**', '**.svg'] # must be the exact opposite of the original workflow
  pull_request:
    paths: ['samples/**', '**.md', '.vscode/**', '**.svg']

# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

jobs:
  build:
    runs-on: [self-hosted, 1ES.Pool=1es-graphdevx-ubuntu-github-latest] 
    steps:
      - run: 'echo "No build required"'