name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore: ['samples/**', '**.md', '.vscode/**', '**.svg']
  pull_request:
    # The branches below must be a subset of the branches above
    paths-ignore: ['samples/**', '**.md', '.vscode/**', '**.svg']

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: 9.0.x
    - name: Restore workloads
      run: dotnet workload restore
    - name: Restore dependencies
      run: dotnet restore DevProxy.sln --locked-mode
    - name: Build
      run: dotnet build DevProxy.sln --no-restore
    # We really should have tests, putting these steps here for when we have a build process
    # - name: Test
    #   run: dotnet test DevProxy.sln --no-build --verbosity normal --collect:"XPlat Code Coverage"
    # - name: Install report generator
    #   run: dotnet tool install --global dotnet-reportgenerator-globaltool
    # - name: Generate coverage report
    #   run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:./reports/coverage
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: coverage
    #     path: reports/coverage
